sudo: false
language: c
cache:
  timeout: 3600
  apt: true
  directories:
    - build_dir/host
    - staging_dir/host
    - tools
    - dl
    - package/feeds
script:
- sh build.sh
deploy:
  provider: releases
  api_key:
  skip_cleanup: true
  file_glob: true
  file: openwrt/bin/x86-glibc/OpenWrt-*.tar.bz2
  on:
    repo: simlelievre/openwrt-build
